# render.yaml
services:
  - type: web
    name: shopquick-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "streamlit run app.py --server.port 10000 --server.enableCORS false"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10